name: TestPlugin
version: '${project.version}'
main: testplugin.testplugin.HotbarLock
api-version: '1.19'
commands:
  hotbarenable:
    description: Enables hotbarlock
    usage: /hotbarenable
    aliases: [hbe, hotbare]
  hotbardisable:
    description: Disable hotbarlock
    usage: /hotbardisable
    aliases: [hbd, hotbard]
